version: '3.9'

services:
  data-access-layer:
    container_name: data-access-layer
    hostname: data-access-layer
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "3090:3090"
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm i && npm run start:dev"
    networks:
      - backend-network

networks:
  backend-network:
    external:
      name: db_default
